services:
  db:
    image: mysql:8.0
    container_name: stockinsights-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  app:
    build: ./app
    container_name: stockinsights-app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
volumes:
  db_data:
